@startuml codecs_lib_components

!if %not(%variable_exists("$COMPONENTS"))
    !include ./Templates/Components2.cuml
!endif

title Components Diagram of the Library codecs_lib

$library(codecs_lib) {
    !if $is_not_defined("$COBS_MODULE")
        !include ./cobs/cobs_components.iuml
    !endif
    
    !if $is_not_defined("$XOR_MODULE")
        !include ./xor_scrambler/xor_scrambler_components.iuml
    !endif

    !if $is_not_defined("$VIGENERE_MODULE")
        !include ./vigenere/vigenere_components.iuml
    !endif

    xor_scrambler -[hidden]- cobs
    
    !if $is_not_defined("$WICHMANN_HILL_MODULE")
        !include ./wichmann_hill/wichmann_hill_components.iuml
    !endif
    
    cobs -[hidden]- wichmann_hill
    vigenere -[hidden]-- wichmann_hill
}

@enduml